[package]
name = "barkley-break"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.82"
js-sys = "0.3.59"
getrandom = { version = "0.2", features = ["js"] }
rand = "^0.8.5"